// Mocks generated by Mockito 5.0.15 from annotations
// in teste_tokenlab/test/presentation/movies/list/movies_list/home_view_widget_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:domain/use_cases/get_movie_list_uc.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:teste_tokenlab/presentation/common/states/states.dart' as _i5;
import 'package:teste_tokenlab/presentation/movies/list/movies_list/home_view_bloc.dart'
    as _i3;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeGetMovieListUc_0 extends _i1.Fake implements _i2.GetMovieListUc {}

class _FakeSink_1<T> extends _i1.Fake implements Sink<T> {}

/// A class which mocks [HomeViewBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeViewBloc extends _i1.Mock implements _i3.HomeViewBloc {
  MockHomeViewBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetMovieListUc get getMovieListUc =>
      (super.noSuchMethod(Invocation.getter(#getMovieListUc),
          returnValue: _FakeGetMovieListUc_0()) as _i2.GetMovieListUc);
  @override
  Sink<void> get tryStartMovies =>
      (super.noSuchMethod(Invocation.getter(#tryStartMovies),
          returnValue: _FakeSink_1<void>()) as Sink<void>);
  @override
  _i4.Stream<_i5.HomeViewState> get onStateChange =>
      (super.noSuchMethod(Invocation.getter(#onStateChange),
              returnValue: Stream<_i5.HomeViewState>.empty())
          as _i4.Stream<_i5.HomeViewState>);
  @override
  void dispose() => super.noSuchMethod(Invocation.method(#dispose, []),
      returnValueForMissingStub: null);
  @override
  String toString() => super.toString();
}
