// Mocks generated by Mockito 5.4.1 from annotations
// in teste_tokenlab/test/presentation/movies/list/movies_list/home_view_widget_test.dart.
// Do not manually edit this file.

// @dart=2.19

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:domain/use_cases/get_movie_list_uc.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:re_state_action/re_state_action.dart' as _i7;
import 'package:rxdart/rxdart.dart' as _i3;
import 'package:teste_tokenlab/presentation/movies/list/movies_list/home_view_bloc.dart'
    as _i5;
import 'package:teste_tokenlab/presentation/movies/list/movies_list/home_view_state.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetMovieListUc_0 extends _i1.SmartFake
    implements _i2.GetMovieListUc {
  _FakeGetMovieListUc_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCompositeSubscription_1 extends _i1.SmartFake
    implements _i3.CompositeSubscription {
  _FakeCompositeSubscription_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHomeViewState_2 extends _i1.SmartFake implements _i4.HomeViewState {
  _FakeHomeViewState_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [HomeViewBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeViewBloc extends _i1.Mock implements _i5.HomeViewBloc {
  MockHomeViewBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetMovieListUc get getMovieListUc => (super.noSuchMethod(
        Invocation.getter(#getMovieListUc),
        returnValue: _FakeGetMovieListUc_0(
          this,
          Invocation.getter(#getMovieListUc),
        ),
      ) as _i2.GetMovieListUc);
  @override
  _i3.CompositeSubscription get subscriptions => (super.noSuchMethod(
        Invocation.getter(#subscriptions),
        returnValue: _FakeCompositeSubscription_1(
          this,
          Invocation.getter(#subscriptions),
        ),
      ) as _i3.CompositeSubscription);
  @override
  _i4.HomeViewState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeHomeViewState_2(
          this,
          Invocation.getter(#state),
        ),
      ) as _i4.HomeViewState);
  @override
  _i6.Stream<_i4.HomeViewState> get stateStream => (super.noSuchMethod(
        Invocation.getter(#stateStream),
        returnValue: _i6.Stream<_i4.HomeViewState>.empty(),
      ) as _i6.Stream<_i4.HomeViewState>);
  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void closeSubscriptions() => super.noSuchMethod(
        Invocation.method(
          #closeSubscriptions,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void initState(_i4.HomeViewState? initialState) => super.noSuchMethod(
        Invocation.method(
          #initState,
          [initialState],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void emitState(_i4.HomeViewState? state) => super.noSuchMethod(
        Invocation.method(
          #emitState,
          [state],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void listenState(
    _i7.ReStateCallback<_i4.HomeViewState>? listener, {
    _i7.ReListenerModifier<_i4.HomeViewState>? modifier,
    Function? onError,
    void Function()? onDone,
    bool? cancelOnError = false,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #listenState,
          [listener],
          {
            #modifier: modifier,
            #onError: onError,
            #onDone: onDone,
            #cancelOnError: cancelOnError,
          },
        ),
        returnValueForMissingStub: null,
      );
  @override
  void removeStateListener(_i7.ReStateCallback<_i4.HomeViewState>? listener) =>
      super.noSuchMethod(
        Invocation.method(
          #removeStateListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void closeState() => super.noSuchMethod(
        Invocation.method(
          #closeState,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void initEvent() => super.noSuchMethod(
        Invocation.method(
          #initEvent,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void on<T extends _i4.HomeViewEvent>(
    _i7.ReEventCallback<T>? callback, {
    _i7.ReListenerModifier<T>? modifier,
    Function? onError,
    void Function()? onDone,
    bool? cancelOnError = false,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [callback],
          {
            #modifier: modifier,
            #onError: onError,
            #onDone: onDone,
            #cancelOnError: cancelOnError,
          },
        ),
        returnValueForMissingStub: null,
      );
  @override
  void process(_i4.HomeViewEvent? event) => super.noSuchMethod(
        Invocation.method(
          #process,
          [event],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void closeEvent() => super.noSuchMethod(
        Invocation.method(
          #closeEvent,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
